name: 'call from other workflow'

on:
  workflow_call:
    inputs:
      work_dir:
        type: string
        required: true
      env:
        type: string
        required: true

jobs:
  terraform:
    name: 'terraform test'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.work_dir }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform help
        run: terraform -help

      - name: check env
        run: echo "env = ${{ inputs.env }}"

      - name: check workdir
        run: echo "work dir = ${{ inputs.work_dir }}"

      - name: file list
        run: ls
