name: Create issue when PR is merged.
on:
  pull_request:
    branches:
      - master
    types: 
      - closed

jobs:
  create_issue:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: List context
        run: echo ${{ github }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: List up added files
        uses: tj-actions/changed-files@v34
        id: list-up-files
      - name: Separete title and body from added file
        id: separate-title
        if: steps.list-up-files.outputs.added_files
        run: |
          for file in ${{ steps.list-up-files.outputs.added_files }}; do
            echo "$file was added"
            file_name=issue_template.md
            echo "file_name=${file_name}" >> $GITHUB_OUTPUT

            echo "title=`head -n 1 ${file}`" >> $GITHUB_OUTPUT
            echo "---" > $file_name
            echo "title: ${title}" >> $file_name
            echo "---" >> $file_name
            cat $file >> $file_name
            break;
          done
      - name: Create Issue
        uses: JasonEtco/create-an-issue@v2
        if: steps.separate-title.outputs.file_name
        with:
          filename: ${{ steps.separate-title.outputs.title }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
