name: Update labels
on:
  push:
    branches:
      - master:
    paths:
      - labels.yaml

jobs:
  update_labels:
    runs_on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Sync labels
        uses: b4b4r07/github-labeler@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
