name: 'call other workflow'

on:
  push:
    paths:
      - ".github/workflows/terraform.yml"
      - ".github/workflows/terraform/terraform.yml"

jobs:
  call-terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      work_dir: md
      env: dev
