name: 'call other workflow'

on:
  push:
    paths:
      - ".github/workflows/terraform.yml"
      - ".github/workflows/terraform/terraform.yml"

jobs:
  terraform:
    name: 'terraform test'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

  call-terraform:
    uses: ./.github/workflows/terraform/terraform.yml
    with:
      work_dir: md
      env: dev
